// @generated by protoc-gen-connect-web v0.3.1 with parameter "target=ts"
// @generated from file message.proto (package message, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {Empty, MethodKind} from "@bufbuild/protobuf";
import {ListResponse} from "./message_pb.js";

/**
 * @generated from service message.MessageService
 */
export const MessageService = {
  typeName: "message.MessageService",
  methods: {
    /**
     * @generated from rpc message.MessageService.List
     */
    list: {
      name: "List",
      I: Empty,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

